version: '2'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  webserver:
    image: phpstorcm/php-71-apache-xdebug-26
    ports:
      - "8848:80"
    volumes:
      - ./:/var/www/html
    links:
      - mysql:mysql
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal